Resolvendo bugs
elitejp/projeto-final-raphael-grupo5 pull request #3
Opened 2022-07-06 20:33 UTC by Gleidson2002

2022-07-06 21:49 UTC, anatrone commented on src/pages/RegisterCareGiver/index.jsx
> +const baseURL = "https://caregiver-and-pets.herokuapp.com"
; no final. Melhor para visualizar o final da linha

2022-07-06 21:50 UTC, anatrone commented on src/pages/RegisterCareGiver/index.jsx
> +
Linhas a mais, tirar o excesso

2022-07-06 21:50 UTC, anatrone commented on src/pages/RegisterCareGiver/index.jsx
> +
Linhas a mais, tirar o excesso

2022-07-06 21:55 UTC, anatrone commented
Quando você criar uma PR para corrigir bugs, o ideal é o commit ser um fix e não uma feat

2022-07-06 21:57 UTC, anatrone approved these changes

2022-07-06 21:57 UTC, anatrone requested changes
Acho valido corrigir o que foi solicitado nos comentarios, mas só se você quiser. (Coloquei como require, mas você pode remover)

2022-07-06 22:10 UTC, anatrone approved these changes

2022-07-06 22:39 UTC, elitejp commented on src/pages/RegisterCareGiver/index.jsx
> +        <StyledDiv  h="auto"  display="flex" w="100%" bc="#68D1E7" >
Como estamos usando a biblioteca styled-compoent, deixar toda estilização no styles.js

2022-07-06 22:59 UTC, elitejp commented on src/pages/RegisterCareGiver/styles.js
> +display: ${(props)=>props.display||"flex"};
Como é um styled-component que vai ser usado apenas nessa pagina, nao precisa "fazer 2x" o trabalho de stilizar, usando as props.
Nice que vc manja bem de usar props de stilização, da pra vermos de fazer components "globais"

2022-07-06 23:04 UTC, elitejp requested changes
Amanhã (07/07), na reunião vou passar uma ideias melhor, que acho q deixei a desejar, falha minha, sobre padrões que talvez tenha falado vermos e tals.
Tem umas dicas comentadas nos change ae.

2022-07-07 14:40 UTC, lmfreire requested changes
Está faltando o retorno do erro para o usuário

2022-07-07 15:44 UTC, Gleidson2002 commented on src/pages/RegisterCareGiver/index.jsx
> +        <StyledDiv  h="auto"  display="flex" w="100%" bc="#68D1E7" >
na proxima vou me esforçar para aplicar isso, mas acho que seria perca de tempo modificar uma coisa que já está pronta e funcional.

2022-07-07 15:45 UTC, elitejp approved these changes
Tranquilo! Concordo com vc, super justo!

2022-07-07 16:11 UTC, lmfreire requested changes
Ainda está faltando o retorno do erro para o usuário quando ele não preenche um campo corretamente

2022-07-07 19:25 UTC, lmfreire approved these changes

2022-07-07 19:43 UTC, merged